{
 "title": "FlowProxy",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": {
     "query": "label_values({order=\"bundle\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Peer count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flowproxy_builderhub_peer_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "User RPS",
   "type": "timeseries",
   "description": "Requests per second on the user endpoint, grouped by method type.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(method) (rate(flowproxy_ingress_rpc_request_duration_count{instance=\"$Instance\", handler=\"user\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Forwarder", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "HTTP call failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "flowproxy_forwarder_http_call_failures{instance=\"$Instance\"}",
     "legendFormat": "{{peer_name}} -- {{reason}}"
    }
   ]
  },
  {
   "title": "HTTP connection failures",
   "type": "timeseries",
   "description": "Errors that occur during a connection establishment.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "flowproxy_forwarder_http_connect_failures{instance=\"$Instance\"}",
     "legendFormat": "{{peer_name}} -- {{reason}}"
    }
   ]
  },
  {
   "title": "RPC call duration (mean & p50)",
   "type": "timeseries",
   "description": "Aggregated over 5 minutes.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, big_request, peer_name) (rate(flowproxy_forwarder_rpc_call_duration_bucket{instance=\"$Instance\"}[5m])))",
     "legendFormat": "p50 {{peer_name}} (big: {{big_request}})"
    },
    {
     "expr": "sum by (big_request, instance, peer_name) (\n  rate(flowproxy_forwarder_rpc_call_duration_sum{instance=\"$Instance\"}[5m])\n)\n/\nsum by (big_request, instance, peer_name) (\n  rate(flowproxy_forwarder_rpc_call_duration_count{instance=\"$Instance\"}[5m])\n)",
     "legendFormat": "mean {{peer_name}} (big: {{big_request}})"
    }
   ]
  },
  {
   "title": "RPC call duration (p99)",
   "type": "timeseries",
   "description": "Aggregated over 5 minutes.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, big_request, peer_name) (rate(flowproxy_forwarder_rpc_call_duration_bucket{instance=\"$Instance\"}[5m])))",
     "legendFormat": "p99 {{peer_name}} (big: {{big_request}})"
    }
   ]
  },
  {
   "title": "Open HTTP connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "flowproxy_forwarder_open_http_connections{instance=\"$Instance\"}",
     "legendFormat": "{{instance}} => {{peer_name}}"
    }
   ]
  },
  {
   "title": "Inflight HTTP requests",
   "type": "timeseries",
   "description": "The number of inflight HTTP requests: requests that were initiated but are still waiting for a response.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum by(instance) (flowproxy_forwarder_inflight_requests{instance=\"$Instance\"})",
     "legendFormat": "total"
    },
    {
     "expr": "flowproxy_forwarder_inflight_requests{instance=\"$Instance\"}",
     "legendFormat": "peer {{peer_name}}"
    }
   ]
  },
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "User eth_sendBundle RPC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, priority) (rate(flowproxy_ingress_rpc_request_duration_bucket{instance=\"$Instance\", method=\"eth_sendBundle\", handler=\"user\"}[5m])))",
     "legendFormat": "p50 {{priority}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, priority) (rate(flowproxy_ingress_rpc_request_duration_bucket{instance=\"$Instance\", method=\"eth_sendBundle\", handler=\"user\"}[5m])))",
     "legendFormat": "p99 {{priority}}"
    }
   ]
  },
  {
   "title": "System eth_sendBundle RPC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, priority) (rate(flowproxy_ingress_rpc_request_duration_bucket{instance=\"$Instance\", method=\"eth_sendBundle\", handler=\"system\"}[5m])))",
     "legendFormat": "p50 {{priority}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, priority) (rate(flowproxy_ingress_rpc_request_duration_bucket{instance=\"$Instance\", method=\"eth_sendBundle\", handler=\"system\"}[5m])))",
     "legendFormat": "p99 {{priority}}"
    }
   ]
  },
  {
   "title": "Signer cache hit ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(handler) (flowproxy_ingress_signer_cache_hit_ratio{instance=\"$Instance\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Order cache hit ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(handler) (flowproxy_ingress_order_cache_hit_ratio{instance=\"$Instance\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Avg payload size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (method) (\n  rate(flowproxy_ingress_request_body_size_bytes_sum{instance=\"$Instance\"}[5m])\n)\n/\nsum by (method) (\n  rate(flowproxy_ingress_request_body_size_bytes_count{instance=\"$Instance\"}[5m])\n)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Open FDs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flowproxy_process_open_fds{instance=\"$Instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flowproxy_process_threads{instance=\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "E2E bundle processing time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, big_request, direction) (rate(flowproxy_system_e2e_bundle_processing_time_bucket{instance=\"$Instance\"}[5m])))",
     "legendFormat": "p50 {{direction}} (big: {{big_request}})"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, big_request, direction) (rate(flowproxy_system_e2e_bundle_processing_time_bucket{instance=\"$Instance\"}[5m])))",
     "legendFormat": "p99 {{direction}} (big: {{big_request}})"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flowproxy_process_cpu_usage{instance=\"$Instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flowproxy_process_resident_memory_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}